name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # ou a branch que você deseja usar para deploy

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: 'ftp'
        local-dir: |
          ./public  # Diretório local 1
          ./src     # Diretório local 2
        server-dir: |
          /public_html  # Diretório de destino para public
          /src          # Diretório de destino para src
